chore: storybook build & test

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -32,8 +32,7 @@ jobs:
           restore-keys: |
             ${{ runner.os }}-yarn-v1
 
-      - name: Install dependencies if cache invalid
-        if: steps.yarn-cache.outputs.cache-hit != 'true'
+      - name: Install dependencies
         run: yarn install
 
       - name: Install jq
@@ -91,35 +90,25 @@ jobs:
           restore-keys: |
             ${{ runner.os }}-yarn-v1
 
-      - name: Install dependencies if cache invalid
-        if: steps.yarn-cache.outputs.cache-hit != 'true'
+      - name: Install dependencies
         run: yarn install
 
       - name: Install jq
         run: sudo apt-get install -y jq
 
-      - name: Run Storybook tests
+      - name: Build Storybook
+        run: yarn build-storybook --output-dir /tmp/storybook || { echo 'Storybook build failed'; exit 1; }
+
+      - name: Run Storybook Tests
         run: |
-          if [ -d ".storybook" ]; then
-            yarn storybook dev -p 6006 & yarn wait-on http://127.0.0.1:6006 && yarn test-storybook --url http://127.0.0.1:6006 || echo "Storybook test failed"
-            if [ -f coverage/coverage-summary.json ]; then
-              TEST_COUNT=$(jq '.total.lines.total' coverage/coverage-summary.json)
-              if [ "$TEST_COUNT" -eq "0" ]; then
-                echo "No Storybook test files found, skipping tests."
-              else
-                echo "Storybook tests ran successfully."
-              fi
+          yarn storybook dev -p 6006 & yarn wait-on http://127.0.0.1:6006 && yarn test-storybook --url http://127.0.0.1:6006 || echo "Storybook test failed"
+          if [ -f coverage/coverage-summary.json ]; then
+            TEST_COUNT=$(jq '.total.lines.total' coverage/coverage-summary.json)
+            if [ "$TEST_COUNT" -eq "0" ]; then
+              echo "No Storybook test files found, skipping tests."
             else
-              echo "No coverage file found, skipping tests."
+              echo "Storybook tests ran successfully."
             fi
           else
-            echo "No Storybook configuration directory found, skipping tests."
+            echo "No coverage file found, skipping tests."
           fi
-
-      - name: Build Storybook
-        run: yarn build-storybook --output-dir /tmp/storybook
-
-      - name: Publish to Chromatic
-        uses: chromaui/action@v1
-        with:
-          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
