chore: action flow 작업 분리

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -1,13 +1,12 @@
-name: CI
+name: test
 
 on:
   pull_request:
     branches: [main]
 
 jobs:
-  test:
+  vitest:
     runs-on: ubuntu-latest
-
     steps:
       - name: Checkout repository
         uses: actions/checkout@v2
@@ -20,38 +19,40 @@ jobs:
       - name: Set YARN_IGNORE_NODE
         run: echo "YARN_IGNORE_NODE=1" >> $GITHUB_ENV
 
-      - name: Install dependencies
-        run: yarn install --immutable
+      - name: Cache yarn dependencies
+        uses: actions/cache@v2
+        id: yarn-cache
+        with:
+          path: |
+            ~/.cache/Cypress
+            node_modules
+          key: ${{ runner.os }}-yarn-v1-${{ hashFiles('**/yarn.lock') }}
+          restore-keys: |
+            ${{ runner.os }}-yarn-v1
+
+      - name: Install dependencies if cache invalid
+        if: steps.yarn-cache.outputs.cache-hit != 'true'
+        run: yarn
 
       - name: Install jq
         run: sudo apt-get install -y jq
 
       - name: Run Vitest tests
         run: |
-          yarn run test:unit --coverage || echo "Vitest failed"
-          if [ -f coverage/coverage-summary.json ]; then
-            TEST_COUNT=$(jq '.total.lines.total' coverage/coverage-summary.json)
-            if [ "$TEST_COUNT" -eq "0" ]; then
-              echo "No Vitest files found, skipping tests."
+          if [ -d "tests" ]; then
+            yarn run test:unit --coverage || echo "Vitest failed"
+            if [ -f coverage/coverage-summary.json ]; then
+              TEST_COUNT=$(jq '.total.lines.total' coverage/coverage-summary.json)
+              if [ "$TEST_COUNT" -eq "0" ]; then
+                echo "No Vitest files found, skipping tests."
+              else
+                echo "Vitest tests ran successfully."
+              fi
             else
-              echo "Vitest tests ran successfully."
+              echo "No coverage file found, skipping tests."
             fi
           else
-            echo "No coverage file found, skipping tests."
-          fi
-
-      - name: Run Storybook tests
-        run: |
-          yarn run storybook:test || echo "Storybook test failed"
-          if [ -f coverage/coverage-summary.json ]; then
-            TEST_COUNT=$(jq '.total.lines.total' coverage/coverage-summary.json)
-            if [ "$TEST_COUNT" -eq "0" ]; then
-              echo "No Storybook test files found, skipping tests."
-            else
-              echo "Storybook tests ran successfully."
-            fi
-          else
-            echo "No coverage file found, skipping tests."
+            echo "No Vitest test directory found, skipping tests."
           fi
 
       - name: Upload coverage to Codecov
@@ -60,3 +61,58 @@ jobs:
           files: ./coverage/lcov.info
           flags: unittests
           name: codecov-umbrella
+
+  storybook:
+    runs-on: ubuntu-latest
+    steps:
+      - name: Checkout repository
+        uses: actions/checkout@v2
+
+      - name: Set up Node.js
+        uses: actions/setup-node@v2
+        with:
+          node-version: "18"
+
+      - name: Set YARN_IGNORE_NODE
+        run: echo "YARN_IGNORE_NODE=1" >> $GITHUB_ENV
+
+      - name: Cache yarn dependencies
+        uses: actions/cache@v2
+        id: yarn-cache
+        with:
+          path: |
+            ~/.cache/Cypress
+            node_modules
+          key: ${{ runner.os }}-yarn-v1-${{ hashFiles('**/yarn.lock') }}
+          restore-keys: |
+            ${{ runner.os }}-yarn-v1
+
+      - name: Install dependencies if cache invalid
+        if: steps.yarn-cache.outputs.cache-hit != 'true'
+        run: yarn
+
+      - name: Install jq
+        run: sudo apt-get install -y jq
+
+      - name: Run Storybook tests
+        run: |
+          if [ -d ".storybook" ]; then
+            yarn storybook dev -p 6006 & yarn wait-on http://127.0.0.1:6006 && yarn test-storybook --url http://127.0.0.1:6006 || echo "Storybook test failed"
+            if [ -f coverage/coverage-summary.json ]; then
+              TEST_COUNT=$(jq '.total.lines.total' coverage/coverage-summary.json)
+              if [ "$TEST_COUNT" -eq "0" ]; then
+                echo "No Storybook test files found, skipping tests."
+              else
+                echo "Storybook tests ran successfully."
+              fi
+            else
+              echo "No coverage file found, skipping tests."
+            fi
+          else
+            echo "No Storybook configuration directory found, skipping tests."
+          fi
+
+      - name: Publish to Chromatic
+        uses: chromaui/action@v1
+        with:
+          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
